version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php-app:/var/www/html
    depends_on:
      - php
      - node
      - python

  php:
    build: ./php-app
    volumes:
      - ./php-app:/var/www/html
    ports:
      - "9000:9000"

  node:
    build: ./node-app
    ports:
      - "3000:3000"
    volumes:
      - ./node-app:/usr/src/app
      - /usr/src/app/node_modules

  python:
    build: ./python-app
    ports:
      - "8001:8000"
    volumes:
      - ./python-app:/app